-- Chat lines and the Japanese the engine makes of them. Regenerate the right-hand side with
--   PRINT=1 lua test/run.lua
-- and read every changed line before accepting it.
--
-- These are what the engine produces today, not what a translator would write. Several read
-- stiffly because the grammar is literal, and that is expected; the list is here to catch
-- lines that get WORSE.
TRANSLATION_CASES = {
	{ "hello", "こんにちは" },
	{ "hi everyone", "こんにちは、みんな" },
	{ "good morning guys", "おはようございます、みんな" },
	{ "how are you?", "お元気ですか？" },
	{ "I'm fine, thanks", "元気です、ありがとう" },
	{ "thank you so much!", "本当にありがとうございます！" },
	{ "ty for the group", "グループありがとう" },
	{ "gg", "いい戦いでした" },
	{ "brb", "すぐ戻ります" },
	{ "lol", "(笑)" },
	{ "no problem", "問題ないです" },
	{ "sorry, my bad", "ごめんなさい、私のミスです" },
	{ "see you tomorrow", "また明日" },
	{ "good night everyone", "おやすみなさい、みんな" },
	{ "welcome to the guild!", "ギルドへようこそ！" },
	{ "nice to meet you", "はじめまして" },
	{ "I don't speak japanese", "私は日本語を話しません" },
	{ "do you speak english?", "あなたは英語を話しますか？" },
	{ "I am new to the game", "私はゲームに新しいです" },
	{ "this game is so fun", "このゲームはとても楽しいです" },
	{ "I love this game", "私はこのゲームが大好きです" },
	{ "where are you from?", "どこの出身ですか？" },
	{ "I am from America", "私はアメリカ出身です" },
	{ "what is your name?", "あなたの名前は何ですか？" },
	{ "my name is Bob", "私の名前はBobです" },
	{ "can you help me?", "手伝ってもらえますか？" },
	{ "can you help me with this quest?", "このクエストを手伝ってもらえますか？" },
	{ "I need help with this boss", "私はこのボスの助けが必要です" },
	{ "please wait for me", "私を待ってください" },
	{ "wait a sec", "ちょっと待って" },
	{ "let's go!", "行こう！" },
	{ "let's go to the dungeon", "ダンジョンに行きましょう" },
	{ "follow me", "ついてきて" },
	{ "come here", "ここに来てください" },
	{ "where is the bank?", "銀行はどこですか？" },
	{ "how do I get to Cyrodiil?", "私はどうやってシロディールに着きますか？" },
	{ "what are you doing?", "あなたは何をしていますか？" },
	{ "I am farming mats", "私は素材を周回しています" },
	{ "I have a question", "私は質問があります" },
	{ "I don't know", "私は知りません" },
	{ "I don't understand", "私は分かりません" },
	{ "what does that mean?", "それはどういう意味ですか？" },
	{ "I think it is broken", "私はそれが壊れていると思います" },
	{ "the quest is bugged", "クエストはバグっています" },
	{ "you have to relog", "あなたは再ログインしなければなりません" },
	{ "I got disconnected", "私は切断されました" },
	{ "the server is so laggy today", "サーバーは今日とても重いです" },
	{ "I will be back in 5 minutes", "私は5分後に戻ります" },
	{ "I have to go, see you later", "私は行かなければなりません、また後で" },
	{ "are you ready?", "あなたは準備ができていますか？" },
	{ "I am ready", "準備OK" },
	{ "is everyone ready?", "みんなは準備ができていますか？" },
	{ "lfg vma", "グループメンバーを探している、vMA" },
	{ "LF1M healer for vSS", "あと1人募集、vSS用のヒーラー" },
	{ "need a tank and a healer", "タンクとヒーラーが必要です" },
	{ "we need 2 more dps", "私たちはあとDPS×2が必要です" },
	{ "I can tank", "私はタンクができます" },
	{ "I can heal if you want", "私は回復できます、よければ" },
	{ "who is the tank?", "タンクは誰ですか？" },
	{ "stack on the boss", "ボスに固まってください" },
	{ "don't stand in the fire", "火に立たないでください" },
	{ "kill the adds first", "先に雑魚を倒してください" },
	{ "we wiped again", "私たちはまた全滅しました" },
	{ "one more try", "もう一度" },
	{ "I died", "死にました" },
	{ "can someone rez me?", "誰か、私を蘇生してもらえますか？" },
	{ "thanks for the rez", "蘇生ありがとう" },
	{ "the boss is dead", "ボスは死んでいます" },
	{ "nice job everyone", "よくやった、みんな" },
	{ "does anyone want to run vet dungeons?", "誰かがベテランダンジョンを周回したいですか？" },
	{ "anyone want to do pledges?", "誰かが誓約をしたいですか？" },
	{ "invite me please", "招待してください" },
	{ "can I join?", "私は参加できますか？" },
	{ "x for invite", "招待希望は x と入力" },
	{ "port to me", "私の所にテレポートしてください" },
	{ "wts gold jewelry, pst", "金の宝飾品を売りたいです、ささやいてください" },
	{ "wtb style mats", "スタイル素材を買いたいです" },
	{ "how much for this?", "これはいくらですか？" },
	{ "it is too expensive", "それは高すぎます" },
	{ "I will pay 10k", "私は10kを払います" },
	{ "is anyone selling soul gems?", "誰かが魂石を売っていますか？" },
	{ "where can I buy a horse?", "私はどこで馬を買えますか？" },
	{ "check the guild trader", "ギルドトレーダーを確認してください" },
	{ "there is a dolmen near the wayshrine", "ウェイシュラインの近くにドルメンがあります" },
	{ "is there a world boss here?", "ここにワールドボスがいますか？" },
	{ "the world boss is at the cave", "ワールドボスは洞窟にいます" },
	{ "I killed the dragon yesterday", "私は昨日ドラゴンクロー砦を倒しました" },
	{ "we are going to fight the dragon", "私たちはドラゴンクロー砦と戦うつもりです" },
	{ "I want to be a vampire", "私はヴァンパイアになりたいです" },
	{ "my character is a dark elf nightblade", "私のキャラクターはダークエルフナイトブレードです" },
	{ "what is your build?", "あなたのビルドは何ですか？" },
	{ "your build is very strong", "あなたのビルドはとても強いです" },
	{ "this set is better", "このセットはもっといいです" },
	{ "the best set for tanks", "タンク用の一番いいセット" },
	{ "I can't find my horse", "私は馬を見つけられません" },
	{ "I lost my sword", "私は剣を失いました" },
	{ "give me the sword", "剣をください" },
	{ "you can have it", "あなたはそれを持っていられます" },
	{ "I sent you a mail", "私はあなたにメールを送りました" },
	{ "did you get my mail?", "あなたは私のメールをもらいましたか？" },
	{ "if you need help, ask me", "もしあなたに助けが必要だったら、私に聞いてください" },
	{ "I can't come because I am busy", "私が忙しいですから、私は来られません" },
	{ "when I was a kid, I played this game", "私が子供だったとき、私はこのゲームを遊びました" },
	{ "he said he is coming", "彼は彼が来ていると言いました" },
	{ "I don't know what to do", "私は何をするべきか知りません" },
	{ "do you know how to get to cyro?", "あなたはシロディールへの着き方を知っていますか？" },
	{ "anyone know where the dolmen is?", "誰かがドルメンがどこか知っていますか？" },
	{ "maybe later", "また今度" },
	{ "I am not sure", "私はよく分かりません" },
	{ "that sounds good", "いいですね" },
	{ "no thanks", "結構です" },
	{ "happy birthday!", "誕生日おめでとう！" },
	{ "congrats on the title", "称号おめでとう" },
	{ "I have been playing for 3 years", "私は3年間遊んでいます" },
	{ "I played this game a lot", "私はたくさんこのゲームを遊びました" },
	{ "the event starts tomorrow", "イベントは明日始まります" },
	{ "maintenance is today", "メンテナンスは今日です" },
	{ "Molag Bal is the boss", "モラグ・バルはボスです" },
	{ "I will log out now", "私は今ログアウトします" },
	{ "good luck and have fun", "頑張って、楽しんで" },
	{ "wts |H1:item:12345:0|h[Sword of Doom]|h pst", "|H1:item:12345:0|h[Sword of Doom]|hを売りたいです、ささやいてください" },
	-- High-school vocabulary and grammar (0.4.19-)
	{ "I usually get up early", "私は普段早く起きます" },
	{ "technology has changed our lives", "技術は私たちの人生を変えました" },
	{ "my grandmother lives in a small village", "私の祖母は小さい村に住んでいます" },
	{ "I realized that the situation was serious", "私は状況が真剣だったと気づきました" },
	{ "its ok", "大丈夫です" },
	{ "its broken", "それは壊れています" },
	{ "the museum is famous for its paintings", "博物館はその絵画で有名です" },
	{ "we have already won", "私たちはもう勝ちました" },
	{ "I really want to go", "私は本当に行きたいです" },
	{ "I have never seen it", "私はそれを見たことがありません" },
	{ "have you ever been to japan?", "あなたは今まで日本に行ったことがありますか？" },
	{ "I am interested in history", "私は歴史に興味があります" },
	{ "she graduated from university last year", "彼女は去年大学を卒業しました" },
	{ "he apologized for the delay", "彼は遅れのことで謝りました" },
	{ "where do you live?", "あなたはどこに住んでいますか？" },
	{ "I am good at math", "私は数学が得意です" },
	{ "we ran out of potions", "私たちはポーションを使い果たしました" },
	{ "he left two years ago", "彼は2年前に出ました" },
	{ "turn left at the bridge", "橋で左に曲がってください" },
	{ "the government should protect the environment", "政府は環境を守るべきです" },
	{ "we need to reduce the pollution", "私たちは汚染を減らす必要があります" },
	{ "please fill out this form", "この用紙に記入してください" },
	{ "can you recommend a good restaurant?", "いいレストランをおすすめしてもらえますか？" },
	{ "the accident happened suddenly", "事故は突然起こりました" },
	{ "the company decided to postpone the meeting", "会社は会議を延期することを決めました" },
	{ "she was reluctant to accept the offer", "彼女は提供を受け入れるのに気が進まなかったです" },
	{ "they abandoned the project because of the budget", "彼らは予算のせいでプロジェクトを見捨てました" },
	{ "the population of the city has increased", "街の人口は増えました" },
	{ "it is difficult to predict the outcome", "結果を予測するのは難しいです" },
	{ "I came to help you", "私はあなたを手伝うために来ました" },
	{ "I forgot to buy milk", "私は牛乳を買うことを忘れました" },
	{ "I used a potion to heal", "私は回復するためにポーションを使いました" },
	{ "we agreed to meet tomorrow", "私たちは明日会うことに賛成しました" },
	{ "it is time to go", "行く時間です" },
	{ "the evidence was insufficient", "証拠は不十分でした" },
	{ "renewable energy is essential for a sustainable future", "再生可能なエネルギーは持続可能な未来のために不可欠です" },
	{ "the teacher emphasized the importance of vocabulary", "先生は語彙の重要性を強調しました" },
	{ "he is witty", "彼は機知に富んでいます" },
	{ "I was born in April", "私は4月に生まれました" },
	{ "according to the news, a typhoon is coming", "ニュースによると、台風は来ています" },
	{ "we go to school by bus", "私たちはバスで学校に行きます" },
	{ "I usually take a shower in the morning", "私は普段朝にシャワーを浴びます" },
	{ "she made a lot of friends at the school festival", "彼女は文化祭でたくさんの友達を作りました" },
	{ "you will miss the train unless you hurry", "あなたが急がなかったら、あなたは電車に乗り遅れます" },
	{ "I caught a cold last week", "私は先週風邪をひきました" },
	{ "despite the rain, we went camping", "雨にもかかわらず、私たちはキャンプに行きました" },
	{ "there is a bakery next to the post office", "郵便局の隣にパン屋があります" },
	{ "my father is a police officer", "私の父は警察官です" },
	{ "I brush my teeth every morning", "私は毎朝歯を磨きます" },
	{ "we met on monday", "私たちは月曜日に会いました" },
	{ "the store opens at 9", "店は9時に開きます" },
	-- Relative clauses, participles, comparison, too...to, wish (0.4.23)
	{ "the man who sold me this sword is a thief", "私にこの剣を売った男性は盗賊です" },
	{ "I lost the sword that I bought yesterday", "私は私が昨日買った剣を失いました" },
	{ "people who play tanks are rare", "タンクを遊ぶ人々はレアです" },
	{ "this is the place where we met", "これは私たちが会った場所です" },
	{ "do you know the player who won?", "あなたは勝ったプレイヤーを知っていますか？" },
	{ "the guy standing there is my friend", "そこに立っている人は私の友達です" },
	{ "the boss that killed us is hard", "私たちを倒したボスは難しいです" },
	{ "the item you need is in the chest", "あなたに必要なアイテムは宝箱にあります" },
	{ "I know a guy who can help", "私は手伝える人を知っています" },
	{ "that is the reason why I quit", "それは私がやめる理由です" },
	{ "I saw a man playing guitar", "私はギターを遊んでいる男性を見ました" },
	{ "the player who won killed me", "勝ったプレイヤーは私を倒しました" },
	{ "is the boss that killed us dead?", "私たちを倒したボスは死んでいますか？" },
	{ "the day when we met", "私たちが会った日" },
	{ "I have a sword made of iron", "私は鉄でできている剣を持っています" },
	{ "it is made of iron", "それは鉄でできています" },
	{ "a tank is stronger than a healer", "タンクはヒーラーより強いです" },
	{ "this is the best set in the game", "これはゲームで一番いいセットです" },
	{ "this build is more expensive than that", "このビルドはそれより高いです" },
	{ "she is as tall as her mother", "彼女は彼女の母と同じくらい高いです" },
	{ "playing a tank is fun", "タンクを遊ぶことは楽しいです" },
	{ "I like playing games with friends", "私はゲームを友達と遊ぶことが好きです" },
	{ "I am too tired to play", "私は疲れすぎて遊べません" },
	{ "I am too busy", "私は忙しすぎます" },
	{ "it is too far to walk", "それは遠すぎて歩けません" },
	{ "I wish I could go", "私は私が行けるといいのに" },
	{ "what do you think about this build?", "このビルドについてどう思いますか？" },
	{ "go to chal i will port", "チャルマン砦に行ってください、私はポートします" },
	-- Online game slang (0.4.22)
	{ "nt", "ドンマイ" },
	{ "gg ez", "楽勝" },
	{ "stop feeding", "死にすぎないで" },
	{ "our healer is inting", "私たちのヒーラーはわざと死んでいます" },
	{ "this boss is overtuned", "このボスは強すぎる調整です" },
	{ "he is so tilted", "彼はとてもイライラしています" },
	{ "carry me pls", "キャリーしてください" },
	{ "rng is bad today", "運は今日悪いです" },
	{ "the devs nerfed my build", "開発者は私のビルドを弱体化しました" },
	{ "queue pop", "マッチしました" },
	{ "who pulled?", "誰が釣った？" },
	{ "skill issue", "腕の問題" },
	{ "the tank is afk", "タンクは離席しています" },
	{ "ffs", "いい加減にして" },
	{ "rekt", "ボコボコにされた" },
	{ "bis gear for tanks", "タンク用の最強装備" },
	{ "afaik the patch is tomorrow", "私の知る限り、パッチは明日です" },
	{ "ikr", "だよね" },
	{ "git gud", "上手くなれ" },
	-- Cyrodiil (translated with the Cyrodiil dictionary first; see run.lua)
	{ "fd down", "正門が破られました" },
	{ "bd down", "裏門が破られました" },
	{ "push fd", "正門を攻めてください" },
	{ "need def at chal", "チャルマン砦で防衛が必要です" },
	{ "rss down", "資源は破られています" },
	{ "farm is under attack", "農場は攻撃を受けています" },
	{ "stack on crown", "グループリーダーに集合" },
	{ "drop siege on the bd", "裏門に攻城兵器を置いてください" },
	{ "zerg inc from fd", "正門から大集団インカミング" },
	{ "we need rams at glade", "私たちはグレイドミスト砦で破城槌が必要です" },
	{ "hold the inner", "内門を守ってください" },
	{ "ad is sieging bd at chal", "アルドメリ・ドミニオンはチャルマン砦で裏門を包囲攻撃しています" },
	{ "dc zerg at kings", "キングクレスト砦にカバナントの大集団" },
	{ "can someone repair the wall?", "誰か、壁を修理してもらえますか？" },
	{ "port to arrius and push fd", "アリウス砦にポートしてください、正門を攻めてください" },
	{ "they flipped the lumbermill", "彼らは製材所を奪いました" },
	{ "we took farragut", "私たちはファラガット砦を取りました" },
	{ "the scroll is at alessia", "星霜の書はアレッシア砦にあります" },
	{ "is anyone defending sej?", "誰かがセヤヌス基地を防衛していますか？" },
	{ "put oils on the fd", "正門に燃え盛る油を置いてください" },
	{ "emp inc", "皇帝インカミング" },
	{ "I have 5 rams", "私は破城槌×5を持っています" },
	{ "bring meatbags", "肉袋を持ってきてください" },
	{ "the door is down, go in", "門は破られています、突入" },
	{ "def", "防衛して" },
	{ "inc", "インカミング" },
	{ "the enemy zerg is at fd", "敵の大集団は正門にいます" },
	{ "ep is pushing chal", "エボンハート・パクトはチャルマン砦を攻めています" },
	{ "is the lumbermill ours?", "製材所は私たちのものですか？" },
	{ "we lost arrius", "私たちはアリウス砦を失いました" },
	{ "who has the crown?", "誰がグループリーダーを持っていますか？" },
	{ "keep is flipped", "砦は奪われています" },
	{ "need 2 more for ic", "インペリアルシティにあと2人が必要です" },
	{ "watch out, ball group at bd", "気をつけて、裏門にボールグループ" },
	{ "chal lit", "チャルマン砦は攻撃されています" },
	{ "fd is lit", "正門は攻撃されています" },
	{ "mine lit", "鉱山は攻撃されています" },
	{ "it is mine", "それは私のものです" },
	{ "lm lit", "製材所は攻撃されています" },
	{ "lumber", "製材所" },
	{ "LFG", "グループメンバーを探している" },
	{ "ty", "ありがとう！" },
	{ "bleaks ua", "侵入者の基地に奇襲" },
	{ "ua at bd", "裏門に奇襲" },
	{ "siege on fd", "正門で包囲攻撃してください" },
	{ "drake fd down", "ドレイクロー砦の正門は破られています" },
	{ "chal fd lit", "チャルマン砦の正門は攻撃されています" },
	{ "chim is at mnem", "チムの星霜の書はムネムの星霜の書にあります" },
	{ "Ni-Mohk", "ニ・モークの星霜の書" },
	{ "Alma Ruma", "アルマ・ルーマの星霜の書" },
	{ "the scroll is at altadoon", "星霜の書はアルタドゥーンの星霜の書にあります" },
	{ "push glade", "グレイドミスト砦を攻めてください" },
	{ "dragon lit", "ドラゴンクロー砦は攻撃されています" },
	{ "WP lit", "ウィンターズ・ピークス基地は攻撃されています" },
	{ "def bruma", "ブルーマの街を防衛してください" },
	{ "BB lit", "ブラックブート砦は攻撃されています" },
	{ "HO lit", "ハルルン基地は攻撃されています" },
	{ "port to BRK", "ブルーロード砦にポートしてください" },
	{ "nik", "ニケリ基地" },
	{ "crops", "クロップスの街" },
	{ "vlas", "ヴラスタルスの街" },
	{ "we took warden", "私たちはウォーデン砦を取りました" },
	{ "ball group inc bd", "裏門にボールグループインカミング" },
	{ "ad inc at chal", "チャルマン砦にアルドメリ・ドミニオンインカミング" },
	{ "dethrone", "廃帝" },
	{ "dethrone inc", "廃帝インカミング" },
	{ "emp got dethroned", "皇帝は廃帝にされました" },
	{ "otw", "向かっている途中" },
	{ "omw to chal", "チャルマン砦に向かっている途中" },
	{ "on my way", "向かっている途中" },
	{ "fd open", "正門は破られています" },
	{ "kc lit", "キングクレスト砦は攻撃されています" },
	{ "king ua", "キングクレスト砦に奇襲" },
	{ "yellow zerg inc", "ドミニオンの大集団インカミング" },
	{ "red ball group at bd", "裏門にパクトのボールグループ" },
	{ "we are poplocked", "私たちは陣営人数の上限です" },
	{ "lowpop bonus", "ローポップ・ボーナス" },
	{ "3bar", "陣営人数バー3本" },
	{ "retake chal", "チャルマン砦を取り戻してください" },
	{ "ignore the chat troll", "チャット荒らしを無視してください" },
	{ "the hammer is at glade", "ヴォレンドラングはグレイドミスト砦にあります" },
	{ "he is salty", "彼はイライラしています" },
	{ "dots and hots", "継続ダメージと継続回復" },
	{ "type x for invite", "招待希望は x と入力" },
	{ "tyfg", "グループありがとう" },
	{ "nice try", "惜しかったね" },
	{ "l2p", "もっと上手くなれ" },
	{ "kill em", "彼らを倒してください" },
	{ "ap tick", "時間経過による同盟ポイント" },
	{ "scroll lost", "星霜の書を失いました" },
	{ "team orange", "チームオレンジ（パクトとドミニオンの結託）" },
	{ "ifd down", "内郭の扉が破られました" },
	{ "chal ifd lit", "チャルマン砦の内郭の扉は攻撃されています" },
	{ "we are cut off", "切断されました" },
	{ "they are cutting glade", "彼らはグレイドミスト砦を切断しています" },
	{ "ram on!", "破城槌に乗って！" },
	{ "need ppl on ram", "破城槌に人が必要です" },
	{ "drop tent at bb", "ブラックブート砦にテントを置いてください" },
	{ "use the transitus", "トランシタスの祠を使ってください" },
	{ "chal milegate down", "チャルマン砦のマイルゲートは破られています" },
	{ "bring wall repair kits", "塁壁石工修理キットを持ってきてください" },
	{ "need fire ballista", "炎バリスタが必要です" },
	{ "winter lit", "ウィンターズ・ピークス基地は攻撃されています" },
	{ "harlun ua", "ハルルン基地に奇襲" },
	{ "fair lit", "フェアユール砦は攻撃されています" },
	{ "push fair fd", "フェアユール砦の正門を攻めてください" },
	{ "fair enough", "なるほど" },
	{ "AD SHOULD B AT ROE", "アルドメリ・ドミニオンはローベック砦にいるべきです" },
	{ "BB GONE FARE GONE BM ROE INNER 80 PERCENT", "ブラックブート砦は奪われています、フェアユール砦は奪われています、ブラッドメイン砦、ローベック砦の内門80パーセント" },
	{ "prep counter for inner", "内門のために対抗攻城兵器を準備してください" },
	{ "fd kings", "キングクレスト砦の正門" },
	{ "fd kings lit", "キングクレスト砦の正門は攻撃されています" },
	{ "dclaw lit", "ドラゴンクロー砦は攻撃されています" },
	{ "stone port to brk", "ブルーロード砦に帰還の石で移動してください" },
	{ "bananas at blk", "侵入者の基地にドミニオン" },
	{ "smurfs inc", "カバナントインカミング" },
	{ "train inc fd", "正門にトレイン（大集団）インカミング" },
	{ "roe inner 80%", "ローベック砦の内門80%" },
	{ "vlast lit", "ヴラスタルスの街は攻撃されています" },
	{ "hammy", "ヴォレンドラングを取得しました" },
	{ "gf", "よい戦いでした" },
	{ "Ich habe keine Zeit heute", "Ich habe keine Zeit heute" },
	{ "こんにちは", "こんにちは" },
	{ "let's not attack", "攻撃しないでおきましょう" },
	{ "let's attack", "攻撃しましょう" },
	{ "you must not attack", "あなたは攻撃してはいけません" },
	{ "you mustn't attack", "あなたは攻撃してはいけません" },
	{ "you must attack", "あなたは攻撃しなければなりません" },
	{ "you do not have to attack", "あなたは攻撃しなくてもいいです" },
	{ "you don't have to attack", "あなたは攻撃しなくてもいいです" },
	{ "you have to attack", "あなたは攻撃しなければなりません" },
	{ "please don't attack", "攻撃しないでください" },
	{ "when you must not attack", "あなたが攻撃してはいけないとき" },
	{ "when you don't have to attack", "あなたが攻撃しなくてもいいとき" },
	-- Omitted clause boundaries and visible fallback for unparsed trailing words.
	{ "defend roe hk will bone", "ローベック砦を防衛してください、砦を修理して味方を回復し、防衛を維持してください、全滅させます" },
	{ "defend roe hk will not bone", "ローベック砦を防衛してください、砦を修理して味方を回復し、防衛を維持してください、全滅させません" },
	{ "defend roe hk can bone", "ローベック砦を防衛してください、砦を修理して味方を回復し、防衛を維持してください、全滅させられます" },
	{ "defend roe hk will quickly bone", "ローベック砦を防衛してください、砦を修理して味方を回復し、防衛を維持してください、速く全滅させます" },
	{ "defend roe bone", "ローベック砦を防衛してください、bone" },
	{ "defend roe will", "ローベック砦を防衛してください、will" },
	{ "I will defend roe", "私はローベック砦を防衛します" },

}
