-- Reviewed vocabulary and spellings; exercise Tokenize -> lookup -> Translate.
return {
    { "bbs", "すぐ戻ります", false },
    { "brt", "すぐそちらに行きます", false },
    { "bbiaf", "少ししたら戻ります", false },
    { "brb irl", "リアルの用事ですぐ戻ります", false },
    { "afk irl", "リアルの用事で離席します", false },
    { "afk bio", "トイレで離席します", false },
    { "oml", "なんてこった", false },
    { "omw back", "そちらに戻っています", false },
    { "bbfn", "ひとまずまたね", false },
    { "ttfn", "ひとまずまたね", false },
    { "l8r", "また後で", false },
    { "cu later", "また後で", false },
    { "cya later", "また後で", false },
    { "cya soon", "また近いうちに", false },
    { "cya tomorrow", "また明日", false },
    { "ltns", "久しぶり", false },
    { "hihi", "こんにちは", false },
    { "heya", "やあ", false },
    { "srry", "ごめん", false },
    { "sowwy", "ごめんね", false },
    { "sry all", "みんなごめん", false },
    { "soz all", "みんなごめん", false },
    { "srry all", "みんなごめん", false },
    { "nps", "問題ないよ", false },
    { "npnp", "問題ないよ", false },
    { "np at all", "全然問題ないよ", false },
    { "no probs", "問題ないよ", false },
    { "no prob", "問題ないよ", false },
    { "aight", "了解", false },
    { "alr", "了解", false },
    { "oki", "了解", false },
    { "okies", "了解", false },
    { "okok", "了解", false },
    { "roger that", "了解", false },
    { "yep yep", "うんうん", false },
    { "tysm all", "みんな本当にありがとう", false },
    { "tysm for help", "助けてくれて本当にありがとう", false },
    { "tysm for the help", "助けてくれて本当にありがとう", false },
    { "thx all", "みんなありがとう", false },
    { "thx for group", "グループありがとう", false },
    { "thx for the group", "グループありがとう", false },
    { "thx for run", "周回ありがとう", false },
    { "thx for the run", "周回ありがとう", false },
    { "thx for rez", "蘇生ありがとう", false },
    { "thx for the rez", "蘇生ありがとう", false },
    { "tyfp", "一緒に遊んでくれてありがとう", false },
    { "tyt", "ゆっくりでいいよ", false },
    { "take your time", "ゆっくりでいいよ", false },
    { "nj", "よくやった", false },
    { "n1", "ナイス", false },
    { "wtg", "よくやった", false },
    { "way to go", "よくやった", false },
    { "wpwp", "ナイスプレイ", false },
    { "wp team", "みんなナイスプレイ", false },
    { "nice clutch", "ナイス逆転", false },
    { "unlucky mate", "惜しかったね", false },
    { "all g", "大丈夫", false },
    { "we good", "大丈夫", false },
    { "my b", "私のミスです", false },
    { "mb all", "みんなごめん、私のミスです", false },
    { "mbmb", "ごめん、私のミスです", false },
    { "mb sry", "私のミスです、ごめん", false },
    { "frfr", "本当にそう", false },
    { "fr fr", "本当にそう", false },
    { "no cap", "嘘じゃないよ", false },
    { "nocap", "嘘じゃないよ", false },
    { "istg", "本当にもう", false },
    { "ong", "誓って本当", false },
    { "bruh", "おいおい", false },
    { "bruv", "おい", false },
    { "ayo", "おいおい", false },
    { "sheesh", "うわ、すごい", false },
    { "pogchamp", "すごい", false },
    { "monkas", "怖い", false },
    { "monkaw", "怖すぎる", false },
    { "pepehands", "悲しい", false },
    { "sadge", "悲しい", false },
    { "copium", "負け惜しみ", false },
    { "hopium", "願望頼み", false },
    { "lmaoo", "爆笑", false },
    { "lmfaooo", "大爆笑", false },
    { "roflmao", "大爆笑", false },
    { "lawl", "笑", false },
    { "lulw", "笑", false },
    { "omegalul", "大爆笑", false },
    { "ikr lol", "本当にそれ（笑）", false },
    { "real talk", "真面目な話", false },
    { "ngl tho", "でも正直に言うと", false },
    { "ngl bro", "正直に言うと", false },
    { "skill diff", "実力差だね", false },
    { "team diff", "チームの実力差だね", false },
    { "tank diff", "タンクの実力差だね", false },
    { "healer diff", "ヒーラーの実力差だね", false },
    { "dps diff", "火力役の実力差だね", false },
    { "gg go next", "お疲れ、次へ行こう", false },
    { "we got this", "私たちならいける", false },
    { "u got this", "あなたならいける", false },
    { "you got this", "あなたならいける", false },
    { "afaict", "私が分かる限り", false },
    { "afair", "覚えている限りでは", false },
    { "iinm", "間違っていなければ", false },
    { "idts", "そうは思わない", false },
    { "idek", "さっぱり分からない", false },
    { "idec", "どうでもいい", false },
    { "lmk", "教えて", false },
    { "lemme know", "教えて", false },
    { "let me know", "教えて", false },
    { "nvm that", "それは忘れて", false },
    { "nvm found it", "見つかったので大丈夫", false },
    { "nvm got it", "解決したので大丈夫", false },
    { "nvm fixed", "直ったので大丈夫", false },
    { "yvw", "どういたしまして", false },
    { "np mate", "気にしないで", false },
    { "fwiw", "参考までに", false },
    { "jsyk", "一応伝えておくと", false },
    { "jic", "念のため", false },
    { "icymi", "見逃していたら", false },
    { "btw ty", "ところでありがとう", false },
    { "welp", "やれやれ", false },
    { "welp gg", "やれやれ、お疲れさま", false },
    { "welp rip", "あーあ、残念", false },
    { "whoopsie", "おっと", false },
    { "smh my head", "やれやれ", false },
    { "smdh", "まったくもう", false },
    { "ffs man", "勘弁してくれ", false },
    { "pvx", "PvEとPvPの両方", false },
    { "lowbie", "低レベルキャラクター", false },
    { "lowbies", "低レベルキャラクター", false },
    { "mule", "倉庫キャラクター", false },
    { "bank alt", "倉庫キャラクター", false },
    { "rngeesus", "乱数の神様", false },
    { "rngeezus", "乱数の神様", false },
    { "rngeezus", "乱数の神様", false },
    { "randoms", "野良メンバー", false },
    { "pre made", "固定グループ", false },
    { "pug run", "野良での攻略", false },
    { "pug raid", "野良レイド", false },
    { "pug tank", "野良タンク", false },
    { "pug healer", "野良ヒーラー", false },
    { "fake tank", "タンク役を偽ったプレイヤー", false },
    { "fake healer", "ヒーラー役を偽ったプレイヤー", false },
    { "fake heal", "ヒーラー役を偽ったプレイヤー", false },
    { "random normal", "ランダムノーマルダンジョン", false },
    { "random vet", "ランダムベテランダンジョン", false },
    { "random veteran", "ランダムベテランダンジョン", false },
    { "rnd", "ランダムノーマルダンジョン", false },
    { "rnds", "ランダムノーマルダンジョン", false },
    { "random daily", "デイリーのランダムダンジョン", false },
    { "vet pledges", "ベテランの誓い", false },
    { "normal pledges", "ノーマルの誓い", false },
    { "non dlc", "非DLC", false },
    { "base game dungeon", "ベースゲームのダンジョン", false },
    { "dlcs", "DLC", false },
    { "normals", "ノーマル難易度", false },
    { "achiev", "実績", false },
    { "achieves", "実績", false },
    { "achis", "実績", false },
    { "cheevos", "実績", false },
    { "achievement run", "実績狙いの攻略", false },
    { "trifecta run", "トリフェクタ狙いの攻略", false },
    { "no death run", "ノーデス狙いの攻略", false },
    { "nodeath", "ノーデス", false },
    { "speed clear", "高速クリア", false },
    { "speedclear", "高速クリア", false },
    { "mt", "メインタンク", false },
    { "ot", "サブタンク", false },
    { "maintank", "メインタンク", false },
    { "offtank", "サブタンク", false },
    { "pocket healer", "専属ヒーラー", false },
    { "pocket heal", "専属ヒール", false },
    { "pocket heals", "専属ヒール", false },
    { "heal check", "回復力チェック", false },
    { "healer check", "回復力チェック", false },
    { "mit check", "ダメージ軽減チェック", false },
    { "mitigation check", "ダメージ軽減チェック", false },
    { "hard enrage", "時間切れの強制全滅", false },
    { "soft enrage", "時間経過での難化", false },
    { "enrage timer", "時間切れまでの制限時間", false },
    { "burn phase", "集中攻撃フェーズ", false },
    { "execute phase", "低体力時のとどめフェーズ", false },
    { "cleave damage", "対象の周囲も巻き込むダメージ", false },
    { "st damage", "単体ダメージ", false },
    { "aoe damage", "範囲ダメージ", false },
    { "pad damage", "意味の薄い火力の水増し", false },
    { "trash mobs", "雑魚敵", false },
    { "trash pull", "雑魚のまとめ戦闘", false },
    { "add wave", "追加の敵の出現", false },
    { "boss cleave", "ボスの巻き込み攻撃", false },
    { "gcd", "グローバルクールダウン", false },
    { "icd", "内部クールダウン", false },
    { "internal cooldown", "内部クールダウン", false },
    { "animation cancel", "モーションキャンセル", false },
    { "animation cancelling", "モーションキャンセル", false },
    { "animation canceling", "モーションキャンセル", false },
    { "ani canceling", "モーションキャンセル", false },
    { "ani cancelling", "モーションキャンセル", false },
    { "light attack weaving", "軽攻撃を挟む操作", false },
    { "heavy attack build", "重攻撃中心のビルド", false },
    { "ha build", "重攻撃中心のビルド", false },
    { "one bar build", "ワンバービルド", false },
    { "onebar", "ワンバー", false },
    { "one bar", "ワンバー", false },
    { "pet sorc", "ペットソーサラー", false },
    { "petsorc", "ペットソーサラー", false },
    { "magsorc", "マジカソーサラー", false },
    { "stamsorc", "スタミナソーサラー", false },
    { "magplar", "マジカテンプラー", false },
    { "stamplar", "スタミナテンプラー", false },
    { "magblade", "マジカナイトブレイド", false },
    { "stamblade", "スタミナナイトブレイド", false },
    { "magdk", "マジカドラゴンナイト", false },
    { "stamdk", "スタミナドラゴンナイト", false },
    { "magden", "マジカウォーデン", false },
    { "stamden", "スタミナウォーデン", false },
    { "magcro", "マジカネクロマンサー", false },
    { "stamcro", "スタミナネクロマンサー", false },
    { "magarc", "マジカアルカニスト", false },
    { "stamarc", "スタミナアルカニスト", false },
    { "healden", "ヒーラーウォーデン", false },
    { "bow build", "弓ビルド", false },
    { "bow bow", "両バー弓のビルド", false },
    { "bowbow", "両バー弓のビルド", false },
    { "snb", "片手武器と盾", false },
    { "sword and shield", "片手武器と盾", false },
    { "destro", "破壊杖", false },
    { "resto", "回復杖", false },
    { "desto", "破壊杖", false },
    { "spammable", "連発する主力スキル", false },
    { "spammables", "連発する主力スキル", false },
    { "stat stick", "能力値を得るための装備", false },
    { "proc set", "条件で効果が発動するセット", false },
    { "proc sets", "条件で効果が発動するセット", false },
    { "body set", "防具枠で揃えるセット", false },
    { "frontbar", "表バー", false },
    { "backbar", "裏バー", false },
    { "fb", "表バー", false },
    { "prog", "攻略練習", false },
    { "progression group", "攻略練習グループ", false },
    { "prog group", "攻略練習グループ", false },
    { "prog run", "攻略練習の回", false },
    { "fresh prog", "最初からの攻略練習", false },
    { "blind prog", "予習なしの攻略練習", false },
    { "reclear", "クリア済みコンテンツの再攻略", false },
    { "reclear run", "クリア済みコンテンツの再攻略", false },
    { "farm run", "周回", false },
    { "farm group", "周回グループ", false },
    { "learning run", "練習の回", false },
    { "learning group", "練習グループ", false },
    { "practice run", "練習の回", false },
    { "training run", "練習の回", false },
    { "clear run", "クリアを目指す回", false },
    { "first clear", "初クリア", false },
    { "first timer", "初挑戦の人", false },
    { "first timers", "初挑戦の人", false },
    { "first time here", "ここは初めてです", false },
    { "parse", "ダミー相手の火力測定", false },
    { "parsing", "ダミー相手の火力測定", false },
    { "parse dummy", "火力測定用ダミー", false },
    { "trial dummy", "試練用の火力測定ダミー", false },
    { "target dummy", "練習用ダミー", false },
    { "raid comp", "レイド編成", false },
    { "group comp", "グループ編成", false },
    { "team comp", "チーム編成", false },
    { "comp", "編成", false },
    { "strat", "攻略方法", false },
    { "strats", "攻略方法", false },
    { "raidwide", "全体攻撃", false },
    { "tankbuster", "タンク向けの大ダメージ攻撃", false },
    { "tank buster", "タンク向けの大ダメージ攻撃", false },
    { "tank swap", "タンク交代", false },
    { "tank swap mechanic", "タンク交代ギミック", false },
    { "aggro reset", "敵の狙いのリセット", false },
    { "threat drop", "敵の狙いが外れること", false },
    { "body pull", "接近による敵の釣り", false },
    { "chain pull", "休みなく敵を釣ること", false },
    { "face pull", "不用意な接近で敵を釣ること", false },
    { "proxy aggro", "接近による敵の反応", false },
    { "heal aggro", "回復で敵に狙われること", false },
    { "heal over time", "継続回復", false },
    { "healing over time", "継続回復", false },
    { "damage over time", "継続ダメージ", false },
    { "single target", "単体対象", false },
    { "single target damage", "単体ダメージ", false },
    { "splash damage", "周囲への巻き込みダメージ", false },
    { "splash heal", "周囲への回復", false },
    { "hot uptime", "継続回復の維持率", false },
    { "dot uptime", "継続ダメージの維持率", false },
    { "buff uptime", "強化効果の維持率", false },
    { "uptime", "効果や攻撃を維持できる時間", false },
    { "boss uptime", "ボスを攻撃できる時間", false },
    { "downtime", "攻撃できない時間", false },
    { "boe", "装備時に譲渡不可", false },
    { "bop", "取得時に譲渡制限", false },
    { "bind on equip", "装備時に譲渡不可", false },
    { "bind on pickup", "取得時に譲渡制限", false },
    { "cod", "代金引換", false },
    { "cash on delivery", "代金引換", false },
    { "price check", "相場確認", false },
    { "pricecheck", "相場確認", false },
    { "vendor trash", "店売り用の不要品", false },
    { "vendor junk", "店売り用の不要品", false },
    { "gold sink", "ゲーム内通貨の回収要素", false },
    { "listing fee", "出品手数料", false },
    { "trading fee", "取引手数料", false },
    { "full stack", "最大数までまとまったアイテム", false },
    { "stack price", "1スタックあたりの価格", false },
    { "unit price", "1個あたりの価格", false },
    { "price per unit", "1個あたりの価格", false },
    { "price per stack", "1スタックあたりの価格", false },
    { "mats included", "素材込み", false },
    { "mats provided", "素材持参", false },
    { "my mats", "素材は自分が用意", false },
    { "have mats", "素材は持っています", false },
    { "your mats", "素材はそちらで用意", false },
    { "lf crafter", "クラフターを探しています", false },
    { "looking for crafter", "クラフターを探しています", false },
    { "lfw", "クラフトの依頼募集中", false },
    { "ltb", "購入希望", false },
    { "obo", "価格相談可", false },
    { "or best offer", "価格相談可", false },
    { "pst offer", "希望価格をささやいてください", false },
    { "pst offers", "希望価格をささやいてください", false },
    { "wts carry", "キャリー代行を売ります", false },
    { "lf7m", "あと7人募集", false },
    { "lf9m", "あと9人募集", false },
    { "lf11m", "あと11人募集", false },
    { "lf1 tank", "タンクをあと1人募集", false },
    { "lf1 healer", "ヒーラーをあと1人募集", false },
    { "lf1 dd", "火力役をあと1人募集", false },
    { "lf1 dps", "火力役をあと1人募集", false },
    { "lf2 dd", "火力役をあと2人募集", false },
    { "lf2 dps", "火力役をあと2人募集", false },
    { "exp only", "経験者のみ", false },
    { "experienced only", "経験者のみ", false },
    { "link achievement", "実績をリンクしてください", false },
    { "link achiev", "実績をリンクしてください", false },
    { "link ach", "実績をリンクしてください", false },
    { "link parse", "火力測定結果を見せてください", false },
    { "need quest", "クエストをやりたいです", false },
    { "need the quest", "クエストをやりたいです", false },
    { "doing quest", "クエスト中です", false },
    { "questing here", "ここでクエスト中です", false },
    { "first time", "初めてです", false },
    { "first run", "初挑戦です", false },
    { "new here", "ここは初めてです", false },
    { "new to this", "これは初めてです", false },
    { "new to tanking", "タンクは不慣れです", false },
    { "new to healing", "ヒーラーは不慣れです", false },
    { "still learning", "まだ練習中です", false },
    { "learning mechs", "ギミックを練習中です", false },
    { "explain mechs", "ギミックを説明してください", false },
    { "anyone need", "欲しい人はいますか", false },
    { "free to take", "自由に持っていってください", false },
    { "all yours", "どうぞ持っていってください", false },
    { "wait for quest", "クエストが終わるまで待ってください", false },
    { "wait for healer", "ヒーラーを待ってください", false },
    { "wait for group", "グループを待ってください", false },
    { "wait for everyone", "全員を待ってください", false },
    { "dont rush", "急がないでください", false },
    { "do not rush", "急がないでください", false },
    { "hard stack", "同じ位置にぴったり重なって集合", false },
    { "soft stack", "少し間隔を空けて集合", false },
    { "stack tightly", "同じ位置にぴったり重なって集合", false },
    { "stack loosely", "少し間隔を空けて集合", false },
    { "spread loosely", "少し間隔を空けて散開", false },
    { "burn boss", "ボスに火力を集中", false },
    { "burn the boss", "ボスに火力を集中", false },
    { "nuke boss", "ボスに火力を集中", false },
    { "nuke the boss", "ボスに火力を集中", false },
    { "focus adds", "追加の敵を優先", false },
    { "kill adds first", "追加の敵を先に倒して", false },
    { "ignore adds", "追加の敵は無視", false },
    { "ignore the adds", "追加の敵は無視", false },
    { "stop dps", "攻撃を止めて", false },
    { "hold dps", "攻撃を止めて待って", false },
    { "save ults", "アルティメットを温存", false },
    { "save ult", "アルティメットを温存", false },
    { "ults ready", "アルティメット準備OK", false },
    { "ult ready", "アルティメット準備OK", false },
    { "ult up", "アルティメット使用可能", false },
    { "ults up", "アルティメット使用可能", false },
    { "ult down", "アルティメット使用不可", false },
    { "ults down", "アルティメット使用不可", false },
    { "rezzing", "蘇生中", false },
    { "resing", "蘇生中", false },
    { "rezz pls", "蘇生してください", false },
    { "res pls", "蘇生してください", false },
    { "rezz please", "蘇生してください", false },
    { "res please", "蘇生してください", false },
    { "need rez", "蘇生してください", false },
    { "need res", "蘇生してください", false },
    { "rez inc", "今から蘇生します", false },
    { "res inc", "今から蘇生します", false },
    { "wipe it", "一度全滅してやり直そう", false },
    { "reset fight", "戦闘をやり直そう", false },
    { "reset the fight", "戦闘をやり直そう", false },
    { "nice pull", "いい挑戦でした", false },
    { "good pull", "いい挑戦でした", false },
    { "one more pull", "もう一度挑戦", false },
    { "last pull", "最後の挑戦", false },
    { "food check", "食事バフを確認して", false },
    { "repair break", "修理休憩", false },
    { "gear broken", "装備が壊れています", false },
    { "brb repair", "修理して戻ります", false },
    { "brb repairs", "修理して戻ります", false },
    { "relogging", "ログインし直しています", false },
    { "reloggin", "ログインし直しています", false },
    { "dced", "切断されました", false },
    { "dc'd", "切断されました", false },
    { "disconnected", "切断されました", false },
    { "got dc", "切断されました", false },
    { "i dced", "切断されました", false },
    { "brb relog", "ログインし直して戻ります", false },
    { "stuck in combat", "戦闘状態が解除されません", false },
    { "cant bar swap", "武器バーを切り替えられません", false },
    { "can not bar swap", "武器バーを切り替えられません", false },
    { "lagging hard", "ラグがひどいです", false },
    { "rubber banding", "ラグで位置が引き戻されます", false },
    { "packet loss", "通信パケットの欠落", false },
    { "high ping", "通信遅延が大きい状態", false },
    { "ping spike", "通信遅延の急増", false },
    { "skill delay", "スキル発動の遅延", false },
    { "skills not firing", "スキルが発動しません", false },
    { "ult dump", "アルティメットを一斉に使って", true },
    { "ulti dump", "アルティメットを一斉に使って", true },
    { "ultimate dump", "アルティメットを一斉に使って", true },
    { "dump ults", "アルティメットを一斉に使って", true },
    { "dump ult", "アルティメットを使って", true },
    { "bomb inc", "範囲バースト攻撃が来る", true },
    { "bomb incoming", "範囲バースト攻撃が来る", true },
    { "bomber inc", "ボマーが来る", true },
    { "ball inc", "ボールグループが来る", true },
    { "ball group inc", "ボールグループが来る", true },
    { "negate down", "魔法無効化フィールドを設置した", true },
    { "negate up", "魔法無効化フィールドを展開中", true },
    { "push together", "一緒に突撃して", true },
    { "push as one", "足並みを揃えて突撃して", true },
    { "stay on crown", "リーダーから離れないで", true },
    { "tight on crown", "リーダーにぴったり集合", true },
    { "back on crown", "リーダーの位置に戻って", true },
    { "do not chase", "深追いしないで", true },
    { "stop chasing", "深追いをやめて", true },
    { "peel for healer", "ヒーラーを狙う敵を引き離して", true },
    { "peel for healers", "ヒーラーを狙う敵を引き離して", true },
    { "peel for me", "私を狙う敵を引き離して", true },
    { "hold block", "防御し続けて", true },
    { "break los", "障害物で敵の射線を切って", true },
    { "stay in los", "射線が通る位置にいて", true },
    { "out of los", "射線が通っていません", true },
    { "los them", "障害物で敵の射線を切って", true },
    { "rez at camp", "前線キャンプで復活して", true },
    { "res at camp", "前線キャンプで復活して", true },
    { "camp on cooldown", "キャンプ復活はクールダウン中", true },
    { "camp cd", "キャンプ復活のクールダウン", true },
    { "siege cap", "攻城兵器の設置上限", true },
    { "siege capped", "攻城兵器が設置上限に達した", true },
    { "burn siege", "敵の攻城兵器を燃やして", true },
    { "burn their siege", "敵の攻城兵器を燃やして", true },
    { "backcap", "手薄な後方拠点の占領", true },
    { "back cap", "手薄な後方拠点の占領", true },
    { "backcapping", "手薄な後方拠点を占領中", true },
    { "resource flip", "資源拠点の占領", true },
    { "rss flip", "資源拠点の占領", true },
    { "no cp", "チャンピオンポイント無効", true },
    { "nocp", "チャンピオンポイント無効", true },
    { "smallscale", "少人数戦", true },
    { "outnumbering", "人数有利", true },
    { "outnumbered fight", "人数不利の戦闘", true },
    { "outnumbered fights", "人数不利の戦闘", true },
    { "zerg surfing", "大集団に便乗する戦い方", true },
    { "zerg surfer", "大集団に便乗するプレイヤー", true },
    { "faction stack", "陣営全体の大集合", true },
    { "crosshealing", "味方同士での相互回復", true },
    { "cross healing", "味方同士での相互回復", true },
    { "heal stacking", "回復効果の重ねがけ", true },
    { "perma block", "常時防御", true },
    { "permablock", "常時防御", true },
    { "permablocker", "常時防御するプレイヤー", true },
    { "perma stun", "行動不能が続く状態", true },
    { "permastun", "行動不能が続く状態", true },
    { "cc immunity", "行動妨害への耐性時間", true },
    { "cc immune", "行動妨害が効かない状態", true },
    { "snare immunity", "鈍足への耐性", true },
    { "immovable pot", "行動妨害耐性ポーション", true },
    { "immov pot", "行動妨害耐性ポーション", true },
    { "detection pot", "隠密看破ポーション", true },
    { "detect pot", "隠密看破ポーション", true },
    { "detect pots", "隠密看破ポーション", true },
    { "siege shield", "攻城兵器シールド", true },
    { "meatbags down", "ミートバッグ・カタパルトを設置した", true },
    { "no hard stack", "密集しないでください", false },
    { "no soft stack", "間隔を空けた集合はしないでください", false },
    { "no ult dump", "アルティメットを一斉に使わないでください", true },
    { "no ulti dump", "アルティメットを一斉に使わないでください", true },
    { "tc", "元気でね", false },
    { "cu", "またね", false },
    { "cul", "また後で", false },
    { "cul8r", "また後で", false },
    { "cu l8r", "また後で", false },
    { "bfn", "ひとまずまたね", false },
    { "b4n", "ひとまずまたね", false },
    { "ttys", "また近いうちに話そう", false },
    { "ttyl8r", "また後で話そう", false },
    { "gn8", "おやすみ", false },
    { "hth", "参考になればうれしいです", false },
    { "ik", "知っています", false },
    { "wya", "今どこにいるの", false },
    { "wru", "どこにいるの", false },
    { "wyd", "何してるの", false },
    { "ftw", "最高", false },
    { "tc all", "みんな元気でね", false },
    { "tc everyone", "みんな元気でね", false },
    { "tc guys", "みんな元気でね", false },
    { "gtg tc", "もう行くね、元気でね", false },
    { "g2g tc", "もう行くね、元気でね", false },
    { "cu tc", "またね、元気でね", false },
    { "bye tc", "またね、元気でね", false },
}
